from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    
    def setupUi(self, Dialog):
        Dialog.setObjectName('Dialog')
        Dialog.resize(1115, 910)
        self.main_layout = QtWidgets.QVBoxLayout(Dialog)
        self.main_layout.setObjectName('main_layout')
        self.main_widget = QtWidgets.QWidget(Dialog)
        self.main_widget.setObjectName('main_widget')
        self.container_layout = QtWidgets.QVBoxLayout(self.main_widget)
        self.container_layout.setObjectName('container_layout')
        self.top_section = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_section.sizePolicy().hasHeightForWidth())
        self.top_section.setSizePolicy(sizePolicy)
        self.top_section.setMaximumSize(QtCore.QSize(16777215, 150))
        self.top_section.setObjectName('top_section')
        self.top_grid = QtWidgets.QGridLayout(self.top_section)
        self.top_grid.setObjectName('top_grid')
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_grid.addItem(spacerItem, 0, 5, 1, 1)
        self.input_field = QtWidgets.QTextEdit(self.top_section)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_field.setFont(font)
        self.input_field.setObjectName('input_field')
        self.top_grid.addWidget(self.input_field, 0, 2, 1, 1)
        self.status_field = QtWidgets.QTextEdit(self.top_section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_field.sizePolicy().hasHeightForWidth())
        self.status_field.setSizePolicy(sizePolicy)
        self.status_field.setMinimumSize(QtCore.QSize(300, 0))
        self.status_field.setMaximumSize(QtCore.QSize(2000, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status_field.setFont(font)
        self.status_field.setObjectName('status_field')
        self.top_grid.addWidget(self.status_field, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_grid.addItem(spacerItem1, 0, 0, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.top_section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMinimumSize(QtCore.QSize(200, 0))
        self.start_button.setMaximumSize(QtCore.QSize(200, 75))
        self.start_button.setObjectName('start_button')
        self.top_grid.addWidget(self.start_button, 2, 3, 1, 1)
        self.stop_button = QtWidgets.QPushButton(self.top_section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setMinimumSize(QtCore.QSize(200, 0))
        self.stop_button.setMaximumSize(QtCore.QSize(200, 75))
        self.stop_button.setObjectName('stop_button')
        self.top_grid.addWidget(self.stop_button, 2, 4, 1, 1)
        self.connect_button = QtWidgets.QPushButton(self.top_section)
        self.connect_button.setMinimumSize(QtCore.QSize(0, 60))
        self.connect_button.setObjectName('connect_button')
        self.top_grid.addWidget(self.connect_button, 0, 3, 2, 2)
        self.container_layout.addWidget(self.top_section)
        self.widget_plot = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot.sizePolicy().hasHeightForWidth())
        self.widget_plot.setSizePolicy(sizePolicy)
        self.widget_plot.setObjectName('widget_plot')
        self.container_layout.addWidget(self.widget_plot)
        self.bottom_section = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_section.sizePolicy().hasHeightForWidth())
        self.bottom_section.setSizePolicy(sizePolicy)
        self.bottom_section.setMaximumSize(QtCore.QSize(16777215, 100))
        self.bottom_section.setObjectName('bottom_section')
        self.bottom_layout = QtWidgets.QHBoxLayout(self.bottom_section)
        self.bottom_layout.setObjectName('bottom_layout')
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_layout.addItem(spacerItem2)
        self.data_button = QtWidgets.QPushButton(self.bottom_section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_button.sizePolicy().hasHeightForWidth())
        self.data_button.setSizePolicy(sizePolicy)
        self.data_button.setMinimumSize(QtCore.QSize(200, 0))
        self.data_button.setMaximumSize(QtCore.QSize(200, 75))
        self.data_button.setObjectName('data_button')
        self.bottom_layout.addWidget(self.data_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_layout.addItem(spacerItem3)
        self.container_layout.addWidget(self.bottom_section)
        self.main_layout.addWidget(self.main_widget)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate('Dialog', 'Dialog'))
        self.start_button.setText(_translate('Dialog', '开始'))
        self.stop_button.setText(_translate('Dialog', '停止'))
        self.connect_button.setText(_translate('Dialog', '连接设备（等待几秒）'))
        self.data_button.setText(_translate('Dialog', '所有数据'))

