"""
Title: UI.py
Author: 吴烨辰
LastEditors: 高迎新
"""
from PyQt5 import QtCore, QtGui, QtWidgets


class UiDialog(object):

    def setup_ui(self, dialog):
        dialog.setObjectName('dialog')
        dialog.resize(1115, 910)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.main_widget = QtWidgets.QWidget(dialog)
        self.main_widget.setObjectName('main_widget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout.setObjectName('verticalLayout')
        self.widget_1 = QtWidgets.QWidget(self.main_widget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(size_policy)
        self.widget_1.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_1.setObjectName('widget_1')
        self.gridLayout = QtWidgets.QGridLayout(self.widget_1)
        self.gridLayout.setObjectName('gridLayout')
        spacer_item = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacer_item, 0, 5, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName('textEdit_2')
        self.gridLayout.addWidget(self.textEdit_2, 0, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget_1)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(size_policy)
        self.textEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(2000, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName('textEdit')
        self.gridLayout.addWidget(self.textEdit, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.widget_1)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(size_policy)
        self.pushButton_start.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_start.setMaximumSize(QtCore.QSize(200, 75))
        self.pushButton_start.setObjectName('pushButton_start')
        self.gridLayout.addWidget(self.pushButton_start, 2, 3, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.widget_1)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(size_policy)
        self.pushButton_close.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_close.setMaximumSize(QtCore.QSize(200, 75))
        self.pushButton_close.setObjectName('pushButton_close')
        self.gridLayout.addWidget(self.pushButton_close, 2, 4, 1, 1)
        self.pushButton_link = QtWidgets.QPushButton(self.widget_1)
        self.pushButton_link.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_link.setObjectName('pushButton_link')
        self.gridLayout.addWidget(self.pushButton_link, 0, 3, 2, 2)
        self.verticalLayout.addWidget(self.widget_1)
        self.widget_plot = QtWidgets.QWidget(self.main_widget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.widget_plot.sizePolicy().hasHeightForWidth())
        self.widget_plot.setSizePolicy(size_policy)
        self.widget_plot.setObjectName('widget_plot')
        self.verticalLayout.addWidget(self.widget_plot)
        self.widget_2 = QtWidgets.QWidget(self.main_widget)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(size_policy)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setObjectName('widget_2')
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_data = QtWidgets.QPushButton(self.widget_2)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.pushButton_data.sizePolicy().hasHeightForWidth())
        self.pushButton_data.setSizePolicy(size_policy)
        self.pushButton_data.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_data.setMaximumSize(QtCore.QSize(200, 75))
        self.pushButton_data.setObjectName('pushButton_data')
        self.horizontalLayout_2.addWidget(self.pushButton_data)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.main_widget)
        self.retranslate_ui(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslate_ui(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate('dialog', 'dialog'))
        self.pushButton_start.setText(_translate('dialog', '开始'))
        self.pushButton_close.setText(_translate('dialog', '停止'))
        self.pushButton_link.setText(_translate('dialog', '连接设备（等待几秒）'))
        self.pushButton_data.setText(_translate('dialog', '所有数据'))
